
version: '3'

services:
  db:
    image: postgres:15.0-alpine
    ports:
      - 5432:5432
    volumes:
      - data-storage:/var/lib/postgresql/data
    environment:
      - DB_PASSWORD=postgres
      - DB_USER=postgres
      - DB_NAME=openapi-ts-template
volumes:
  data-storage: